name: Release addon 
on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  release:
    uses: meta/workflows/.forgejo/workflows/wow-release.yml@master
    runs-on: docker
    secrets: inherit
    with:
      github: 'csmith/wow-spec-switch'
      wowinterface-addon-id: '27126'
      curseforge-project-id: '1570381'
